# Generated by Django 4.1.3 on 2023-03-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='title',
        ),
    ]
