# Generated by Django 4.1.3 on 2023-03-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_rename_product_name_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_name',
            new_name='product',
        ),
    ]
