# Generated by Django 4.1.3 on 2023-03-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0003_rename_product_name_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
