# Generated by Django 4.1.3 on 2023-03-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0004_delete_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_name',
        ),
    ]
