# Generated by Django 4.1.3 on 2023-03-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0005_rename_product_cart_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_name',
            new_name='product',
        ),
    ]
