# Generated by Django 4.1.7 on 2023-03-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("APIapp", "0006_rename_product_name_cart_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="user", new_name="farmer",
        ),
    ]
