# Generated by Django 4.1.7 on 2023-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIapp", "0007_rename_user_product_farmer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                choices=[
                    ("APL", "Apple"),
                    ("BAN", "Banana"),
                    ("BLKBR", "Black Berries"),
                    ("BLUBR", "Blue Berries"),
                    ("BRJL", "Brinjal"),
                    ("BITGU", "Bitter Gourd"),
                    ("CAPSI", "Capsicum"),
                    ("CBG", "Cabbage"),
                    ("Chili", "Chili"),
                ],
                max_length=10,
            ),
        ),
    ]
