# Generated by Django 4.1.7 on 2023-03-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIapp", "0008_alter_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                choices=[
                    ("APL", "Apple"),
                    ("BAN", "Banana"),
                    ("BLKBR", "Black Berries"),
                    ("BLUBR", "Blue Berries"),
                    ("BRJL", "Brinjal"),
                    ("BITGU", "Bitter Gourd"),
                    ("CAPSI", "Capsicum"),
                    ("CBG", "Cabbage"),
                    ("Chili", "Chili"),
                    ("Cherry", "Cherries"),
                    ("CustApp", "Custard Apple"),
                    ("ClustBeans", "cluster Beans"),
                    ("EleTusjOk", "Elephant Tusk Okra"),
                    ("FB", "Flat Beans"),
                    ("ginger", "Ginger"),
                    ("Grps", "Grapes"),
                    ("Guava", "Guava"),
                    ("mlbCuc", "malabar Cucumber"),
                    ("Mango", "Mango"),
                    ("Onion", "Onion"),
                    ("Okra", "Okra"),
                    ("Orange", "Orange"),
                    ("Pine Apple", "Pine Apple"),
                    ("Pear", "Pear"),
                    ("Plumps", "Plumps"),
                    ("Papaya", "Papaya"),
                    ("Pumpkins", "PumpKins"),
                    ("Pigeon Pea", "Pigeon Pea"),
                    ("Potato", "Potato"),
                    ("snake Cucu", "Snake Cucumber"),
                    ("Tarmeric", "Tarmeric"),
                    ("WaterMelon", "Water Melon"),
                    ("WaterSpinach", "Water Spinach"),
                ],
                max_length=15,
            ),
        ),
    ]
