# Generated by Django 4.1.7 on 2023-03-24 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("APIapp", "0009_alter_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="farmer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                choices=[
                    ("APL", "Apple"),
                    ("BAN", "Banana"),
                    ("BLKBR", "Black Berries"),
                    ("BLUBR", "Blue Berries"),
                    ("BRJL", "Brinjal"),
                    ("BITGU", "Bitter Gourd"),
                    ("CAPSI", "Capsicum"),
                    ("CBG", "Cabbage"),
                    ("Chili", "Chili"),
                    ("Cherry", "Cherries"),
                    ("CustApp", "Custard Apple"),
                    ("ClustBeans", "cluster Beans"),
                    ("EleTusjOk", "Elephant Tusk Okra"),
                    ("FB", "Flat Beans"),
                    ("ginger", "Ginger"),
                    ("Grps", "Grapes"),
                    ("Guava", "Guava"),
                    ("mlbCuc", "malabar Cucumber"),
                    ("Mango", "Mango"),
                    ("Onion", "Onion"),
                    ("Okra", "Okra"),
                    ("Orange", "Orange"),
                    ("Pine Apple", "Pine Apple"),
                    ("Carrot", "Carrot"),
                    ("Pear", "Pear"),
                    ("Plumps", "Plumps"),
                    ("Papaya", "Papaya"),
                    ("Pumpkins", "PumpKins"),
                    ("Pigeon Pea", "Pigeon Pea"),
                    ("Potato", "Potato"),
                    ("snake Cucu", "Snake Cucumber"),
                    ("Tarmeric", "Tarmeric"),
                    ("WaterMelon", "Water Melon"),
                    ("WaterSpinach", "Water Spinach"),
                ],
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="OrderPlaced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Packed", "Packed"),
                            ("On the way", "On the way"),
                            ("Delivered", "Delevered"),
                            ("Cancle", "Cancle"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="APIapp.customer",
                    ),
                ),
                (
                    "product_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APIapp.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
