# Generated by Django 4.1.3 on 2023-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0011_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(choices=[('KG', 'KG'), ('ML', 'ML'), ('Dozen', 'Dozen'), ('Piece', 'Piece')], default='KG', max_length=15),
        ),
    ]
