# Generated by Django 3.2.4 on 2023-05-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0015_alter_customer_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
