# Generated by Django 3.2.4 on 2023-05-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0018_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegitable', 'Vegitable'), ('Fruits', 'Fruits'), ('Milk', 'Milk'), ('Fish', 'Fish')], max_length=50),
        ),
    ]
